### ISSUE TITLE
Any way I can help with this?

### ISSUE THREAD

**Issue by erichocean** [josephg/sharedb#1]
GitHub has removed the ability to message people, so I'm making this an "issue". I'm very interested in seeing a (hopefully dependency-free) C version of ShareJS, and would love to help out.

**Comment by josephg** [comment]
I'm josephg at gmail if you prefer email.

I'd love some help - though the code is still really thrown together. What are your thoughts about libuv? I'd like to shed dependancies too, but I don't understand kpoll/epoll/etc well enough at the moment to replace it, and I'd lose windows compatibility by doing so.

Things that need doing: 
- More OT types (I want to port across the JSON stuff into libot, though thats going to be super tricky)
- Unit tests
- Make the OT database support save ops to disk
- Flesh out the network protocol (what I'm working on at the moment)
- Make a network client library to talk to it
- Make it easy to build on linux & windows
- Like a million other things.

What are you keen to take a stab at?

**Comment by erichocean** [comment]
libuv is good if you're looking for cross-platform networking, and since it's maintained by the Node people, I think it's a good idea.

I'm most interested in getting the JSON stuff into libot. Why do you think that'll be tricky?

**Comment by josephg** [comment]
Um, largely because C doesn't have any built in dictionary types. I'm not sure what the best approach is there. Whats your preferred plan for objects?
